[package]
name = "UsefulUtilities"
namespace = "doombubbles"
description = "Adds an assortment of minor utilities to BTD6."
websiteUrl = "https://github.com/doombubbles/UsefulUtilities"

[package.dependencies]
LavaGang-MelonLoader = "0.7.3"
doombubbles-Btd6ModHelper = "3.6.5"

[build]
icon = "./Icon.png"
readme = "./README.md"
outdir = "bin"

[[build.copy]]
source = "./bin/Release/UsefulUtilities.dll"
target = "UsefulUtilities.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = ["bloons-td-6"]
categories = ["mods"]
